# updated 2025-03-03 13:48EST
services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx
    restart: unless-stopped
    networks:
      - frontend
      - backend
    ports:
      - "443:443"
    volumes:
      - ssl:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
      LETSENCRYPT_HOST: ${HOSTNAME}

  acme:
    image: nginxproxy/acme-companion:latest
    volumes_from:
      - nginx:rw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: ${CERT_EMAIL}
      NGINX_PROXY_CONTAINER: nginx
    
  teampass-web:
    image: dormancygrace/teampass:latest
    restart: unless-stopped
    command: --hostname=${HOSTNAME}
    ports:
      - 829:80
      - 429:443
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
      LETSENCRYPT_HOST: ${HOSTNAME}
      VIRTUAL_PORT: 80
      # uncomment if certificate's file name doesn't match VIRTUAL_HOST
      #CERT_NAME: YOUR_CERTIFICATE
    volumes:
      - ./teampass-html:/var/www/html
    # uncomment ports to use without proxy
    #ports:
    #  - 80:80
    networks:
      - teampass-internal
      - backend
    depends_on:
      - db

  db:
    restart: unless-stopped
    image: yobasystems/alpine-mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_USER: ${MYSQL_USER_NAME}
    volumes:
      - ./teampass-db:/var/lib/mysql
    networks:
      - teampass-internal

networks:
  frontend:
  backend:
    external: true
  teampass-internal:
